apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        # Automatically inject a sidecar proxy.
        "consul.hashicorp.com/connect-inject": "true"
        # Set the protocol to HTTP in the service defaults.
        "consul.hashicorp.com/connect-service-protocol": "http"
    spec:
      containers:
      - name: currency
        image: nicholasjackson/fake-service:v0.9.0
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "NAME"
          value: "currency"
        - name: "MESSAGE"
          value: "$200"

---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  selector:
    app: currency
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090